orbs:
  react: thefrontside/react@0.2.0
version: 2.1
workflows:
  push:
    jobs:
      - react/install
      - react/eslint:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install
          - run:
              name: "React test suites"
              command: yarn test --ci --runInBand --reporters="jest-junit"
              enviroment: 
                JEST_JUNIT_OUTPUT_DIR: "reports/jest-junit.xml"
          - store_test_results:
              path: reports
          - store_artifacts:
              path: reports/junit
      - react/coverage:
          requires:
            - react/install