orbs:
  react: thefrontside/react@0.2.0
version: 2.1
workflows:
  push:
    jobs:
      - test:
          steps:
            - store_test_results:
                path: reports
            - store_artifacts:
                path: reports
      - react/install
      - react/eslint:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install
      - react/coverage:
          requires:
            - react/install